-- 코드를 작성해주세요
WITH RECURSIVE ECOLI AS (
SELECT ID,PARENT_ID, 1 AS DEPTH FROM ECOLI_DATA WHERE PARENT_ID IS NULL UNION ALL
    SELECT E.ID,E.PARENT_ID, H.DEPTH+1 AS DEPTH FROM ECOLI_DATA E
    JOIN ECOLI H
    ON H.ID=E.PARENT_ID
)
SELECT ID FROM ECOLI
WHERE DEPTH=3
ORDER BY 1 ASC