-- 코드를 작성해주세요
SELECT I.ITEM_ID AS ITEM_ID, I.ITEM_NAME AS ITEM_NAME, I.RARITY AS RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID=T.ITEM_ID
WHERE T.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC