-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, ROUND(FEE) AS FEE
FROM (
    SELECT C.CAR_ID AS CAR_ID, C.CAR_TYPE AS CAR_TYPE, C.DAILY_FEE*(100-P.DISCOUNT_RATE)*30/100 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    RIGHT JOIN (SELECT DISCOUNT_RATE, CAR_TYPE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN  WHERE DURATION_TYPE='30일 이상') AS P
    ON C.CAR_TYPE=P.CAR_TYPE

    WHERE C.CAR_TYPE IN ('SUV','세단') AND 
    C.CAR_ID NOT IN 
    (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H WHERE H.START_DATE <='2022-11-30' AND  H.END_DATE >='2022-11-01')

) T
WHERE FEE>= 500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
