SELECT ID,
    CASE
        WHEN SIZERANK=1 THEN 'CRITICAL'
        WHEN SIZERANK=2 THEN 'HIGH'
        WHEN SIZERANK=3 THEN 'MEDIUM'
        WHEN SIZERANK=4 THEN 'LOW'
    END AS COLONY_NAME 
FROM 
    (
    SELECT ID, 
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZERANK
        FROM ECOLI_DATA        
) as RankedColony
ORDER BY ID;