-- 코드를 입력하세요
SELECT YEAR, MONTH, COUNT(*) AS PURCHASED_USERS, ROUND(COUNT(*)/
    (SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED)='2021'),1) TOTAL_USER
FROM(
    SELECT YEAR(O.SALES_DATE) AS YEAR,  U.USER_ID, MONTH(O.SALES_DATE) AS MONTH
    FROM USER_INFO U
    LEFT JOIN ONLINE_SALE O
    ON O.USER_ID=U.USER_ID
    WHERE O.ONLINE_SALE_ID IS NOT NULL AND YEAR(JOINED)='2021'
    GROUP BY MONTH(O.SALES_DATE), YEAR(O.SALES_DATE), U.USER_ID
    ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC
    ) UT
GROUP BY YEAR, MONTH
