-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID)/
    (SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED)='2021'),1) TOTAL_USER
    FROM USER_INFO U
    LEFT JOIN ONLINE_SALE O
    ON O.USER_ID=U.USER_ID
    WHERE O.ONLINE_SALE_ID IS NOT NULL AND YEAR(JOINED)='2021'
    GROUP BY MONTH(O.SALES_DATE), YEAR(O.SALES_DATE)
    ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC

