-- 코드를 작성해주세요
WITH RECURSIVE GEN AS(
SELECT ID,PARENT_ID,1 AS DEPTH
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
UNION ALL
SELECT E.ID,E.PARENT_ID, GEN.DEPTH+1 AS DEPTH
FROM GEN
JOIN ECOLI_DATA E
ON E.PARENT_ID=GEN.ID
WHERE E.PARENT_ID=GEN.ID
)

SELECT COUNT(*) AS COUNT, P.DEPTH AS GENERATION
FROM GEN P
LEFT JOIN ECOLI_DATA C
ON P.ID=C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY P.DEPTH

