-- 코드를 작성해주세요
SELECT E.EMP_NO, E.EMP_NAME,
  
 (CASE
    WHEN G.SCORE>=96 THEN 'S'
    WHEN G.SCORE>=90 THEN 'A'
    WHEN G.SCORE>=80 THEN 'B'
   ELSE 'C'
END ) GRADE,

CASE
    WHEN G.SCORE>=96 THEN SAL*0.2
    WHEN G.SCORE>=90 THEN SAL*0.15
    WHEN G.SCORE>=80 THEN SAL*0.10
    ELSE 0
END AS BONUS
FROM (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) G
LEFT JOIN HR_EMPLOYEES E
ON G.EMP_NO=E.EMP_NO
ORDER BY E.EMP_NO ASC

