SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM 
    (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
     GROUP BY CAR_ID
     HAVING COUNT(*) >= 5) I
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON H.CAR_ID = I.CAR_ID
WHERE H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(H.START_DATE), H.CAR_ID
ORDER BY MONTH(H.START_DATE) ASC, H.CAR_ID DESC;
