-- 코드를 작성해주세요
SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, MS-D.SIZE_OF_COLONY AS YEAR_DEV, D.ID AS ID
FROM ECOLI_DATA D
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MS
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) M
ON YEAR(D.DIFFERENTIATION_DATE)= M.YEAR
ORDER BY YEAR(D.DIFFERENTIATION_DATE) ASC, MS-D.SIZE_OF_COLONY ASC

