SELECT FI.ID AS ID, NI.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO NI
ON FI.FISH_TYPE=NI.FISH_TYPE
WHERE FI.LENGTH=(SELECT MAX(LENGTH) FROM FISH_INFO WHERE FI.FISH_TYPE=FISH_TYPE)
ORDER BY FI.ID ASC