-- 코드를 입력하세요
SELECT B.CATEGORY AS CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY BOOK_ID
)S
ON S.BOOK_ID=B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
 