-- 코드를 입력하세요
SELECT  CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM(
    SELECT ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS 'RANK', CATEGORY, PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
        )T
WHERE T.RANK=1 AND (T.CATEGORY = '과자' OR T.CATEGORY = '국' OR T.CATEGORY = '김치' OR T.CATEGORY = '식용유')
ORDER BY PRICE DESC
        
      
        
       

